const BSC_CHAIN_ID = process.env.NEXT_PUBLIC_BSC_CHAIN_ID as string;
const BSC_CHAIN_ID_HEX = process.env.NEXT_PUBLIC_BSC_CHAIN_ID_HEX as string;
const BSC_CHAIN_NAME = process.env.NEXT_PUBLIC_BSC_CHAIN_NAME as string;
const BSC_BLOCK_EXPLORER_URL = process.env
	.NEXT_PUBLIC_BSC_BLOCK_EXPLORER_URL as string;
const BSC_RPC_URL = process.env.NEXT_PUBLIC_BSC_RPC_URL as string;
const SIGN_MESSAGE = process.env.NEXT_PUBLIC_SIGN_MESSAGE;

export {
	BSC_CHAIN_ID,
	BSC_CHAIN_ID_HEX,
	BSC_CHAIN_NAME,
	BSC_RPC_URL,
	BSC_BLOCK_EXPLORER_URL,
	SIGN_MESSAGE,
};
